# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
ruby '2.4.0'
gem 'rspec', '3.6.0'
gem 'coderay', '1.1.1'
gem 'rack-test', '0.7.0'
gem 'sinatra', '2.1.0'
gem 'base64'
gem 'sequel', '4.48.0'
gem 'sqlite3', '1.3.13'
gem 'ox'
